name: python-app

on: push
jobs:
  build:
    runs-on: puzl-ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: clean
        run: make clean
      - name: check-lint
        run: make lint
      - name: run unit test
        run: make test
